services:
  db:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  api:
    restart: unless-stopped
    volumes: []

  worker:
    restart: unless-stopped
    volumes: []

  beat:
    restart: unless-stopped
    volumes: []
