services:
  db:
    restart: unless-stopped
    ports: []

  redis:
    restart: unless-stopped
    ports: []

  api:
    restart: unless-stopped

  worker:
    restart: unless-stopped

  beat:
    restart: unless-stopped
