"""add one admin constraint

Revision ID: d3e5f3196bbb
Revises: a49768c0f7f6
Create Date: 2026-06-12 21:39:06.393610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e5f3196bbb'
down_revision: Union[str, Sequence[str], None] = 'a49768c0f7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('one_admin', 'users', ['role'], unique=True, postgresql_where=sa.text("role = 'admin'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_admin', table_name='users', postgresql_where=sa.text("role = 'admin'"))
    # ### end Alembic commands ###
